/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.jp23.view;

import edunova.jp23.controller.ObradaArtikl;
import edunova.jp23.controller.ObradaStavka;
import edunova.jp23.controller.ObradaDobavljac;
import edunova.jp23.controller.ObradaKupac;
import edunova.jp23.controller.ObradaNarudzba;
import edunova.jp23.controller.ObradaOperater;
import edunova.jp23.model.Artikl;
import edunova.jp23.model.Stavka;
import edunova.jp23.model.Dobavljac;
import edunova.jp23.model.Entitet;
import edunova.jp23.model.Kupac;
import edunova.jp23.model.Narudzba;
import edunova.jp23.model.Operater;
import edunova.jp23.util.EdunovaException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.Date;
import java.util.List;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Pozna
 */
public class Izbornik extends javax.swing.JFrame {

    private ObradaNarudzba obradaN;
    private ObradaOperater obradaO;
    private ObradaKupac obradaK;
    private ObradaStavka obradaS;
    private ObradaArtikl obradaA;
    private ObradaDobavljac obradaD;
    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        setTitle(Aplikacija.NASLOV_APP + " " + 
                Aplikacija.operater.getImePrezime());
        new Vrijeme().start();
        
        obradaN=new ObradaNarudzba();
        obradaO=new ObradaOperater();
        obradaS=new ObradaStavka();
        obradaA=new ObradaArtikl();
        obradaD=new ObradaDobavljac();
        obradaK=new ObradaKupac();
        obradaS=new ObradaStavka();
        ucitajKupce();
        ucitajEntitete();
        ucitajDobavljaceCmb();
        ucitajA();
        ucitajD();
        ucitajK();
        ucitajO();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lblVrijeme = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        paneNarudzba = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNarudzbe = new javax.swing.JList<>();
        lblBrojRacuna = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelZap = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        btnUkloni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTrenutniDatum = new javax.swing.JLabel();
        lblTrenutniZaposlenik = new javax.swing.JLabel();
        lblUkCijena = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstSveStavke = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnDodajUNarudzbu = new javax.swing.JButton();
        btnUkloniIzNarudzbe = new javax.swing.JButton();
        cmbKupci = new javax.swing.JComboBox<>();
        btnUredi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTrenutneStavke = new javax.swing.JList<>();
        txtPretraga = new javax.swing.JTextField();
        btnPretraga = new javax.swing.JButton();
        lblDatum = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblZaposlenik = new javax.swing.JLabel();
        paneDobavljac = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtAdresaDobavljaca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstDobavljaci = new javax.swing.JList<>();
        btnDodajDobavljaca = new javax.swing.JButton();
        btnUrediDobavljaca = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNazivDobavljaca = new javax.swing.JTextField();
        txtImeVlasnikaDobavljaca = new javax.swing.JTextField();
        btnUkloniDobavljaca = new javax.swing.JButton();
        btnTraziDobavljace = new javax.swing.JButton();
        txtTraziDobavljace = new javax.swing.JTextField();
        paneZaposlenik = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstZaposlenici = new javax.swing.JList<>();
        btnUrediZaposlenik = new javax.swing.JButton();
        btnDodajZaposlenik = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnUkloniZaposlenik = new javax.swing.JButton();
        txtPrezime = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtOib = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtIban = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pwdZaporkaZaposlenika = new javax.swing.JPasswordField();
        paneArtikl = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstArtikli = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        btnDodajArtikl = new javax.swing.JButton();
        btnUrediArtikl = new javax.swing.JButton();
        btnUkloniArtikl = new javax.swing.JButton();
        txtNazivArtikla = new javax.swing.JTextField();
        txtCijenaArtikla = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cmbDobavljaci = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txtPretraziArtikli = new javax.swing.JTextField();
        btnPretragaArtikli = new javax.swing.JButton();
        paneKupci = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstKupci = new javax.swing.JList<>();
        txtImeKupca = new javax.swing.JTextField();
        txtPrezimeKupca = new javax.swing.JTextField();
        txtEmailKupca = new javax.swing.JTextField();
        txtKontaktKupca = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtAdresaKupca = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtOibKupca = new javax.swing.JTextField();
        btnDodajKupca = new javax.swing.JButton();
        btnUrediKupca = new javax.swing.JButton();
        btnUkloniKupca = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        btnPretraziKupca = new javax.swing.JButton();
        txtPretraziKupce = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        lblVrijeme.setText("Vrijeme");
        jToolBar1.add(lblVrijeme);

        paneNarudzba.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                paneNarudzbaComponentShown(evt);
            }
        });

        lstNarudzbe.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstNarudzbeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstNarudzbe);

        lblBrojRacuna.setText("Broj Računa:");

        jLabel3.setText("Ukupna cijena");

        jLabel4.setText("Kupac");

        jLabel5.setText("Datum");

        jLabelZap.setText("Zaposlenik");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnUkloni.setText("Ukloni");
        btnUkloni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(lstSveStavke);

        jLabel2.setText("Artikli narudžbe");

        jLabel8.setText("Svi artikli");

        btnDodajUNarudzbu.setText("<<");
        btnDodajUNarudzbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajUNarudzbuActionPerformed(evt);
            }
        });

        btnUkloniIzNarudzbe.setText(">>");
        btnUkloniIzNarudzbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniIzNarudzbeActionPerformed(evt);
            }
        });

        btnUredi.setText("Uredi");
        btnUredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrediActionPerformed(evt);
            }
        });

        lstTrenutneStavke.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTrenutneStavkeValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstTrenutneStavke);

        btnPretraga.setText("Traži");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        lblDatum.setText(" ");

        jLabel7.setText(" ");

        javax.swing.GroupLayout paneNarudzbaLayout = new javax.swing.GroupLayout(paneNarudzba);
        paneNarudzba.setLayout(paneNarudzbaLayout);
        paneNarudzbaLayout.setHorizontalGroup(
            paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNarudzbaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneNarudzbaLayout.createSequentialGroup()
                        .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelZap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBrojRacuna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUkCijena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblZaposlenik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbKupci, javax.swing.GroupLayout.Alignment.LEADING, 0, 175, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUredi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneNarudzbaLayout.createSequentialGroup()
                        .addComponent(btnDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addGap(47, 47, 47)
                        .addComponent(btnUkloni, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGap(33, 33, 33)
                .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneNarudzbaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnUkloniIzNarudzbe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDodajUNarudzbu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                            .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnPretraga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPretraga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTrenutniDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTrenutniZaposlenik, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147))
        );
        paneNarudzbaLayout.setVerticalGroup(
            paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNarudzbaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneNarudzbaLayout.createSequentialGroup()
                        .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneNarudzbaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4))
                            .addGroup(paneNarudzbaLayout.createSequentialGroup()
                                .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblBrojRacuna)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paneNarudzbaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(paneNarudzbaLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(lblUkCijena, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabelZap)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblZaposlenik, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbKupci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(btnUredi)
                                                .addGap(18, 18, 18)
                                                .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(btnUkloni)
                                                    .addComponent(btnDodaj)))
                                            .addGroup(paneNarudzbaLayout.createSequentialGroup()
                                                .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblTrenutniDatum)
                                                    .addGroup(paneNarudzbaLayout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(btnPretraga)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(paneNarudzbaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneNarudzbaLayout.createSequentialGroup()
                                                        .addComponent(lblTrenutniZaposlenik)
                                                        .addGap(61, 61, 61))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneNarudzbaLayout.createSequentialGroup()
                                                        .addComponent(btnDodajUNarudzbu)
                                                        .addGap(16, 16, 16)
                                                        .addComponent(btnUkloniIzNarudzbe)
                                                        .addGap(31, 31, 31)))
                                                .addComponent(jLabel1)
                                                .addGap(47, 47, 47))))
                                    .addGroup(paneNarudzbaLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane2)))))
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );

        tabbedPane.addTab("Narudžba", paneNarudzba);

        paneDobavljac.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                paneDobavljacComponentShown(evt);
            }
        });

        jLabel10.setText("Ime vlasnika");

        jLabel11.setText("Adresa");

        lstDobavljaci.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDobavljaciValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstDobavljaci);

        btnDodajDobavljaca.setText("Dodaj");
        btnDodajDobavljaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajDobavljacaActionPerformed(evt);
            }
        });

        btnUrediDobavljaca.setText("Uredi");
        btnUrediDobavljaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrediDobavljacaActionPerformed(evt);
            }
        });

        jLabel12.setText("Svi dobavljači");

        jLabel13.setText("Naziv dobavljača");

        btnUkloniDobavljaca.setText("Ukloni");
        btnUkloniDobavljaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniDobavljacaActionPerformed(evt);
            }
        });

        btnTraziDobavljace.setText("Traži");
        btnTraziDobavljace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziDobavljaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneDobavljacLayout = new javax.swing.GroupLayout(paneDobavljac);
        paneDobavljac.setLayout(paneDobavljacLayout);
        paneDobavljacLayout.setHorizontalGroup(
            paneDobavljacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDobavljacLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(paneDobavljacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneDobavljacLayout.createSequentialGroup()
                        .addComponent(btnDodajDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUrediDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUkloniDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneDobavljacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNazivDobavljaca)
                        .addComponent(txtImeVlasnikaDobavljaca)
                        .addComponent(txtAdresaDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(paneDobavljacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneDobavljacLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneDobavljacLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(paneDobavljacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneDobavljacLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnTraziDobavljace, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneDobavljacLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txtTraziDobavljace, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        paneDobavljacLayout.setVerticalGroup(
            paneDobavljacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDobavljacLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(paneDobavljacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneDobavljacLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGroup(paneDobavljacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneDobavljacLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneDobavljacLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtTraziDobavljace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTraziDobavljace))))
                    .addGroup(paneDobavljacLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNazivDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImeVlasnikaDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdresaDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addGroup(paneDobavljacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUrediDobavljaca)
                            .addComponent(btnDodajDobavljaca)
                            .addComponent(btnUkloniDobavljaca))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Dobavljač", paneDobavljac);

        paneZaposlenik.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                paneZaposlenikComponentShown(evt);
            }
        });

        jLabel14.setText("E-Mail");

        lstZaposlenici.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstZaposleniciValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lstZaposlenici);

        btnUrediZaposlenik.setText("Uredi");
        btnUrediZaposlenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrediZaposlenikActionPerformed(evt);
            }
        });

        btnDodajZaposlenik.setText("Dodaj");
        btnDodajZaposlenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajZaposlenikActionPerformed(evt);
            }
        });

        jLabel15.setText("Ime");

        btnUkloniZaposlenik.setText("Ukloni");
        btnUkloniZaposlenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniZaposlenikActionPerformed(evt);
            }
        });

        jLabel16.setText("Zaposlenici");

        jLabel17.setText("Prezime");

        jLabel18.setText("OIB");

        jLabel19.setText("IBAN");

        jLabel20.setText("Zaporka");

        javax.swing.GroupLayout paneZaposlenikLayout = new javax.swing.GroupLayout(paneZaposlenik);
        paneZaposlenik.setLayout(paneZaposlenikLayout);
        paneZaposlenikLayout.setHorizontalGroup(
            paneZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneZaposlenikLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(paneZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneZaposlenikLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(paneZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneZaposlenikLayout.createSequentialGroup()
                        .addGroup(paneZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIban)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOib)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtIme))
                        .addGap(81, 81, 81)
                        .addGroup(paneZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDodajZaposlenik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUrediZaposlenik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUkloniZaposlenik, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdZaporkaZaposlenika, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        paneZaposlenikLayout.setVerticalGroup(
            paneZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneZaposlenikLayout.createSequentialGroup()
                .addGroup(paneZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneZaposlenikLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneZaposlenikLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(paneZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneZaposlenikLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnDodajZaposlenik))
                            .addGroup(paneZaposlenikLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUrediZaposlenik))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneZaposlenikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUkloniZaposlenik))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwdZaporkaZaposlenika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Zaposlenik", paneZaposlenik);

        paneArtikl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                paneArtiklComponentShown(evt);
            }
        });

        lstArtikli.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstArtikliValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(lstArtikli);

        jLabel21.setText("Artikli");

        btnDodajArtikl.setText("Dodaj");
        btnDodajArtikl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajArtiklActionPerformed(evt);
            }
        });

        btnUrediArtikl.setText("Uredi");
        btnUrediArtikl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrediArtiklActionPerformed(evt);
            }
        });

        btnUkloniArtikl.setText("Ukloni");
        btnUkloniArtikl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniArtiklActionPerformed(evt);
            }
        });

        jLabel22.setText("Cijena");

        jLabel23.setText("Naziv");

        jLabel24.setText("Dobavljač");

        btnPretragaArtikli.setText("Traži");
        btnPretragaArtikli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaArtikliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneArtiklLayout = new javax.swing.GroupLayout(paneArtikl);
        paneArtikl.setLayout(paneArtiklLayout);
        paneArtiklLayout.setHorizontalGroup(
            paneArtiklLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneArtiklLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(paneArtiklLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneArtiklLayout.createSequentialGroup()
                        .addGroup(paneArtiklLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNazivArtikla, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneArtiklLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbDobavljaci, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCijenaArtikla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                        .addGroup(paneArtiklLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneArtiklLayout.createSequentialGroup()
                                .addComponent(txtPretraziArtikli, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneArtiklLayout.createSequentialGroup()
                                .addComponent(btnPretragaArtikli, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))))
                    .addGroup(paneArtiklLayout.createSequentialGroup()
                        .addComponent(btnDodajArtikl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUrediArtikl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUkloniArtikl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(paneArtiklLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneArtiklLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneArtiklLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        paneArtiklLayout.setVerticalGroup(
            paneArtiklLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneArtiklLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneArtiklLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazivArtikla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPretraziArtikli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneArtiklLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCijenaArtikla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretragaArtikli))
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbDobavljaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneArtiklLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajArtikl)
                    .addComponent(btnUrediArtikl)
                    .addComponent(btnUkloniArtikl))
                .addGap(45, 45, 45))
            .addGroup(paneArtiklLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Artikli", paneArtikl);

        paneKupci.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                paneKupciComponentShown(evt);
            }
        });

        lstKupci.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstKupciValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(lstKupci);

        jLabel25.setText("Ime");

        jLabel26.setText("Prezime");

        jLabel27.setText("Email");

        jLabel28.setText("Kontakt");

        jLabel29.setText("Adresa");

        jLabel30.setText("OIB");

        btnDodajKupca.setText("Dodaj");
        btnDodajKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajKupcaActionPerformed(evt);
            }
        });

        btnUrediKupca.setText("Uredi");
        btnUrediKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrediKupcaActionPerformed(evt);
            }
        });

        btnUkloniKupca.setText("Ukloni");
        btnUkloniKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniKupcaActionPerformed(evt);
            }
        });

        jLabel31.setLabelFor(lstKupci);
        jLabel31.setText("Kupci");

        btnPretraziKupca.setText("Traži");
        btnPretraziKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziKupcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneKupciLayout = new javax.swing.GroupLayout(paneKupci);
        paneKupci.setLayout(paneKupciLayout);
        paneKupciLayout.setHorizontalGroup(
            paneKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneKupciLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(paneKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(paneKupciLayout.createSequentialGroup()
                        .addGroup(paneKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPrezimeKupca)
                                .addComponent(txtEmailKupca, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImeKupca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(paneKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKontaktKupca)
                            .addComponent(txtAdresaKupca)
                            .addComponent(txtOibKupca, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneKupciLayout.createSequentialGroup()
                        .addComponent(btnDodajKupca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUrediKupca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(btnUkloniKupca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(paneKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPretraziKupce, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneKupciLayout.createSequentialGroup()
                        .addComponent(btnPretraziKupca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneKupciLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(103, 103, 103))
        );
        paneKupciLayout.setVerticalGroup(
            paneKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneKupciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(paneKupciLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(paneKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneKupciLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImeKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrezimeKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneKupciLayout.createSequentialGroup()
                        .addGroup(paneKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneKupciLayout.createSequentialGroup()
                                .addComponent(txtPretraziKupce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretraziKupca)
                                .addGap(17, 17, 17))
                            .addGroup(paneKupciLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKontaktKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdresaKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(paneKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneKupciLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneKupciLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOibKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajKupca)
                    .addComponent(btnUrediKupca)
                    .addComponent(btnUkloniKupca))
                .addGap(32, 32, 32))
        );

        tabbedPane.addTab("Kupac", paneKupci);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstZaposleniciValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstZaposleniciValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        if (lstZaposlenici.getSelectedValue() == null) {
            return;
        }
        
        obradaO.setEntitet(lstZaposlenici.getSelectedValue());

        // ovo se može zamijeniti tkz. Binding
        txtIme.setText(obradaO.getEntitet().getIme());
        txtPrezime.setText(obradaO.getEntitet().getPrezime());

        try {
            txtEmail.setText(obradaO.getEntitet().getEmail());
        } catch (Exception e) {
            txtEmail.setText("");
        }

        try {
            txtOib.setText(obradaO.getEntitet().getOib());
        } catch (Exception e) {
            txtOib.setText("");
        }

        try {
            txtIban.setText(obradaO.getEntitet().getIban());
        } catch (Exception e) {
            txtIban.setText("");
        }

    }//GEN-LAST:event_lstZaposleniciValueChanged

    private void btnUrediZaposlenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrediZaposlenikActionPerformed
        if (obradaO.getEntitet()==null ||
            obradaO.getEntitet().getId() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
        postaviVrijednostiNaEntitetO();

        try {
            obradaO.update();
            pocistiO();
            ucitajO();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnUrediZaposlenikActionPerformed

    private void btnDodajZaposlenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajZaposlenikActionPerformed
        obradaO.setEntitet(new Operater());
        postaviVrijednostiNaEntitetO();

        try {
            obradaO.create();
            pocistiO();
            ucitajO();
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getPoruka());
        }
    }//GEN-LAST:event_btnDodajZaposlenikActionPerformed

    private void lstArtikliValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstArtikliValueChanged
         if (evt.getValueIsAdjusting()) {
            return;
        }

        if (lstArtikli.getSelectedValue() == null) {
            return;
        }

        obradaA.setEntitet(lstArtikli.getSelectedValue());
        
        var g= obradaA.getEntitet();

        // ovo se može zamijeniti tkz. Binding
        txtNazivArtikla.setText(obradaA.getEntitet().getNaziv());
        txtCijenaArtikla.setText(obradaA.getEntitet().getCijena().toString());
        cmbDobavljaci.setSelectedItem(g.getDobavljac());


       
    }//GEN-LAST:event_lstArtikliValueChanged

    private void btnDodajArtiklActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajArtiklActionPerformed
        obradaA.setEntitet(new Artikl());
        postaviVrijednostiNaEntitetA();

        try {
            obradaA.create();
            pocistiA();
            ucitajA();
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getPoruka());
        }
    }//GEN-LAST:event_btnDodajArtiklActionPerformed

    private void btnDodajKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajKupcaActionPerformed
        obradaK.setEntitet(new Kupac());
        postaviVrijednostiNaEntitetK();

        try {
            obradaK.create();
            pocistiK();
            ucitajK();
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getPoruka());
        }
    }//GEN-LAST:event_btnDodajKupcaActionPerformed

    private void btnUrediArtiklActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrediArtiklActionPerformed
        if (obradaA.getEntitet()==null ||
            obradaA.getEntitet().getId() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
        postaviVrijednostiNaEntitetA();

        try {
            obradaA.update();
            pocistiA();
            ucitajA();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnUrediArtiklActionPerformed


    private void btnUrediDobavljacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrediDobavljacaActionPerformed
        if (obradaD.getEntitet()==null ||
            obradaD.getEntitet().getId() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
        postaviVrijednostiNaEntitetD();

        try {
            obradaD.update();
            pocistiD();
            ucitajD();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnUrediDobavljacaActionPerformed

    private void btnDodajDobavljacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajDobavljacaActionPerformed
        obradaD.setEntitet(new Dobavljac());
        postaviVrijednostiNaEntitetD();

        try {
            obradaD.create();
            pocistiD();
            ucitajD();
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getPoruka());
        }
    }//GEN-LAST:event_btnDodajDobavljacaActionPerformed

    private void lstDobavljaciValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDobavljaciValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        if (lstDobavljaci.getSelectedValue() == null) {
            return;
        }

        obradaD.setEntitet(lstDobavljaci.getSelectedValue());

        // ovo se može zamijeniti tkz. Binding
        txtNazivDobavljaca.setText(obradaD.getEntitet().getNaziv());
        try {
            txtImeVlasnikaDobavljaca.setText(obradaD.getEntitet().getImeVlasnika());
        } catch(Exception e) {
            txtImeVlasnikaDobavljaca.setText("");
        }
        try {
            txtAdresaDobavljaca.setText(obradaD.getEntitet().getAdresa());
        } catch (Exception e) {
            txtAdresaDobavljaca.setText("");
        }
        
    }//GEN-LAST:event_lstDobavljaciValueChanged

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        DefaultListModel<Artikl> m = new DefaultListModel<>();
        m.addAll(obradaA.getPodaci(txtPretraga.getText()));
        lstSveStavke.setModel(m);
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnUrediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrediActionPerformed
        if (obradaN.getEntitet()==null || 
                obradaN.getEntitet().getId() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }if(cmbKupci.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(rootPane, "Odaberite kupca");
    }
        postaviVrijednostiNaEntitet();

        try {
            obradaN.update();
            pocisti();
            ucitajEntitete();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnUrediActionPerformed

    private void btnUkloniIzNarudzbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniIzNarudzbeActionPerformed
        if(lstTrenutneStavke.getSelectedValue()==null){
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite artikl");
            return;
        }
        
        
        DefaultListModel<Stavka> m;
        try {
            m=(DefaultListModel<Stavka>) lstTrenutneStavke.getModel();
            m.get(0).toString();
        } catch (Exception e) {
           return;
        }
        
        
       
        for(Stavka s: lstTrenutneStavke.getSelectedValuesList()){
               try {
                obradaS.setEntitet(s);
                obradaS.delete();
                m.removeElementAt(lstTrenutneStavke.getSelectedIndex());
            } catch (EdunovaException e) {
              System.out.println(e.getPoruka());
            }
            try {
                obradaS.update();
            } catch (EdunovaException e) {
                System.out.println(e.getPoruka());
            }
               
               
        }
        

        
        lstNarudzbe.getSelectedValue().setUkupnaCijena(updateUkupnaCijena());
       lstTrenutneStavke.setModel(m);
       
       postaviVrijednostiNaEntitet();
       postavljanjeVrijednosti();
        
        lstTrenutneStavke.repaint();
        
        
          
       
    }//GEN-LAST:event_btnUkloniIzNarudzbeActionPerformed

    private void btnDodajUNarudzbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajUNarudzbuActionPerformed
        if(lstSveStavke.getSelectedValue()==null){
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite artikl");
            return;
        }
        
        if(lstNarudzbe.getSelectedValue()==null){
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite narudžbu");
            return;
        }
        
        DefaultListModel<Stavka> m;
        
        
        
        
        try {
            m=(DefaultListModel<Stavka>) lstTrenutneStavke.getModel();
            m.get(0).toString();
        } catch (Exception e) {
            m= new DefaultListModel<>();
            lstTrenutneStavke.setModel(m);
        }
//       if (lstTrenutneStavke.getSelectedValue() == null) {
//            return;
//        }

         
       for(Artikl a : lstSveStavke.getSelectedValuesList()){
               Stavka s = new Stavka();
               s.setNarudzba(lstNarudzbe.getSelectedValue());
               s.setArtikl(a);
               obradaS.setEntitet(s);
               m.addElement(s);
       }
       try {
                obradaS.update();
            } catch (EdunovaException e) {
              System.out.println(e.getPoruka());
            }
       lstNarudzbe.getSelectedValue().setUkupnaCijena(updateUkupnaCijena());
       lstTrenutneStavke.setModel(m);
       
       postaviVrijednostiNaEntitet();
       postavljanjeVrijednosti();
        
        lstTrenutneStavke.repaint();
    }//GEN-LAST:event_btnDodajUNarudzbuActionPerformed

    private void btnUkloniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniActionPerformed
         if (obradaN.getEntitet()==null || 
                obradaN.getEntitet().getId() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
         System.out.println("Veličina: "+lstTrenutneStavke.getModel().getSize());
         
         for(Stavka s:obradaS.getPodaci()){
             if(s.getNarudzba()==lstNarudzbe.getSelectedValue()){
                 try {
                     obradaS.setEntitet(s);
                     obradaS.delete();
                 } catch (EdunovaException e) {
                     System.out.println(e.getPoruka());
                 }
             }
         }
         
        DefaultListModel<Stavka> m = (DefaultListModel<Stavka>) lstTrenutneStavke.getModel();
        m.removeAllElements();
         
        try {
            obradaN.delete();
            pocisti();
            ucitajEntitete();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnUkloniActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        if(cmbKupci.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite kupca");
            return;
        }
        obradaN.setEntitet(new Narudzba());
        
        DefaultListModel<Stavka> m;
        try {
            m=(DefaultListModel<Stavka>) lstTrenutneStavke.getModel();
            m.get(0).toString();
        } catch (Exception e) {
            m= new DefaultListModel<>();
            lstTrenutneStavke.setModel(m);
        }
        
        m.removeAllElements();
        postaviVrijednostiNaEntitet();
        
        
        try {
            obradaN.create();
            pocisti();
            ucitajEntitete();
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getPoruka());
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void lstNarudzbeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstNarudzbeValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        if (lstNarudzbe.getSelectedValue() == null) {
            return;
        }

        obradaN.setEntitet(lstNarudzbe.getSelectedValue());

        postavljanjeVrijednosti();
        
        var g= obradaN.getEntitet();

        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        
        
        lblZaposlenik.setText(Aplikacija.operater.getImePrezime());
        lblBrojRacuna.setText("Broj računa: "+ g.getId());
        cmbKupci.setSelectedItem(g.getKupac());
        lblDatum.setText(df.format(g.getDatum()));
        lstNarudzbe.getSelectedValue().setUkupnaCijena(updateUkupnaCijena());
        lblUkCijena.setText(g.ukupnaCijenaToString());
        
        DefaultListModel<Stavka> m = new DefaultListModel<>();
        m.addAll(g.getArtikli());
        lstTrenutneStavke.setModel(m);
        lstTrenutneStavke.repaint();
        
    }//GEN-LAST:event_lstNarudzbeValueChanged

    private void paneDobavljacComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_paneDobavljacComponentShown
        ucitajD();
    }//GEN-LAST:event_paneDobavljacComponentShown

    private void paneZaposlenikComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_paneZaposlenikComponentShown
        ucitajO();
    }//GEN-LAST:event_paneZaposlenikComponentShown

    private void paneArtiklComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_paneArtiklComponentShown
        ucitajA();
        ucitajDobavljaceCmb();
    }//GEN-LAST:event_paneArtiklComponentShown

    private void paneKupciComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_paneKupciComponentShown
        ucitajK();
    }//GEN-LAST:event_paneKupciComponentShown

    private void paneNarudzbaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_paneNarudzbaComponentShown

        ucitajEntitete();
        ucitajKupce();
    }//GEN-LAST:event_paneNarudzbaComponentShown

    private void btnUkloniArtiklActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniArtiklActionPerformed
         if (obradaA.getEntitet()==null || 
                obradaA.getEntitet().getId() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
        
         for(Stavka s:obradaS.getPodaci()){
             if(s.getArtikl()==lstArtikli.getSelectedValue()){
                 try {
                     obradaS.setEntitet(s);
                     obradaS.delete();
                 } catch (EdunovaException e) {
                     System.out.println(e.getPoruka());
                 }
             }
         }
         

        try {
            obradaA.delete();
            pocistiA();
            ucitajA();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnUkloniArtiklActionPerformed

    private void btnUkloniDobavljacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniDobavljacaActionPerformed
         if (obradaD.getEntitet()==null || 
                obradaD.getEntitet().getId() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
         
         for(Artikl a:obradaA.getPodaci()){
             for(Stavka s:obradaS.getPodaci()){
                 if(s.getArtikl()==a){
                     try {
                     obradaS.setEntitet(s);
                     obradaS.delete();
                 } catch (EdunovaException e) {
                     System.out.println(e.getPoruka());
                 }
                 }
             
             }
             if(a.getDobavljac()==lstDobavljaci.getSelectedValue()){
                 try {
                     obradaA.setEntitet(a);
                     obradaA.delete();
                 } catch (EdunovaException e) {
                     System.out.println(e.getPoruka());
                 }
         }
             }

        try {
            obradaD.delete();
            pocistiD();
            pocistiA();
            pocisti();
            ucitajD();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnUkloniDobavljacaActionPerformed

    private void btnPretragaArtikliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaArtikliActionPerformed
         DefaultListModel<Artikl> m = new DefaultListModel<>();
        m.addAll(obradaA.getPodaci(txtPretraziArtikli.getText()));
        lstArtikli.setModel(m);
    }//GEN-LAST:event_btnPretragaArtikliActionPerformed

    private void lstKupciValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstKupciValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        if (lstKupci.getSelectedValue() == null) {
            return;
        }

        obradaK.setEntitet(lstKupci.getSelectedValue());

        var g= obradaK.getEntitet();

        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        
        
        txtAdresaKupca.setText(g.getAdresa());
        txtEmailKupca.setText(g.getEmail());
        txtKontaktKupca.setText(g.getKontakt());
        txtOibKupca.setText(g.getOib());
        txtImeKupca.setText(g.getIme());
        txtPrezimeKupca.setText(g.getPrezime());
    }//GEN-LAST:event_lstKupciValueChanged

    private void btnUrediKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrediKupcaActionPerformed
        if (obradaK.getEntitet()==null || 
                obradaK.getEntitet().getId() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
        postaviVrijednostiNaEntitetK();

        try {
            obradaK.update();
            pocistiK();
            ucitajK();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }

    }//GEN-LAST:event_btnUrediKupcaActionPerformed

    private void btnUkloniKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniKupcaActionPerformed
        if (obradaK.getEntitet()==null || 
                obradaK.getEntitet().getId() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
        
        for(Narudzba n:obradaN.getPodaci()){
             if(n==lstNarudzbe.getSelectedValue()){
                 
                 try {
                     obradaN.setEntitet(n);
                     obradaN.delete();
                 } catch (EdunovaException ex) {
                     Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
         }
        
        

        try {
            obradaK.delete();
            pocistiK();
            ucitajK();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnUkloniKupcaActionPerformed

    private void btnUkloniZaposlenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniZaposlenikActionPerformed
        if (obradaO.getEntitet()==null || 
                obradaO.getEntitet().getId() == null) {
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite stavku");
            return;
        }
        
        for(Narudzba n:obradaN.getPodaci()){
             if(n==lstNarudzbe.getSelectedValue()){
                 
                 try {
                     obradaN.setEntitet(n);
                     obradaN.delete();
                 } catch (EdunovaException ex) {
                     Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
         }

        try {
            obradaO.delete();
            pocistiO();
            ucitajO();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnUkloniZaposlenikActionPerformed

    private void btnTraziDobavljaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziDobavljaceActionPerformed
        DefaultListModel<Dobavljac> m = new DefaultListModel<>();
        m.addAll(obradaD.getPodaci(txtTraziDobavljace.getText()));
        lstDobavljaci.setModel(m);
    }//GEN-LAST:event_btnTraziDobavljaceActionPerformed

    private void btnPretraziKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziKupcaActionPerformed
        DefaultListModel<Kupac> m = new DefaultListModel<>();
        m.addAll(obradaK.getPodaci(txtPretraziKupce.getText()));
        lstKupci.setModel(m);
    }//GEN-LAST:event_btnPretraziKupcaActionPerformed

    private void lstTrenutneStavkeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTrenutneStavkeValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstTrenutneStavkeValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Izbornik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Izbornik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Izbornik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Izbornik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Izbornik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajArtikl;
    private javax.swing.JButton btnDodajDobavljaca;
    private javax.swing.JButton btnDodajKupca;
    private javax.swing.JButton btnDodajUNarudzbu;
    private javax.swing.JButton btnDodajZaposlenik;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnPretragaArtikli;
    private javax.swing.JButton btnPretraziKupca;
    private javax.swing.JButton btnTraziDobavljace;
    private javax.swing.JButton btnUkloni;
    private javax.swing.JButton btnUkloniArtikl;
    private javax.swing.JButton btnUkloniDobavljaca;
    private javax.swing.JButton btnUkloniIzNarudzbe;
    private javax.swing.JButton btnUkloniKupca;
    private javax.swing.JButton btnUkloniZaposlenik;
    private javax.swing.JButton btnUredi;
    private javax.swing.JButton btnUrediArtikl;
    private javax.swing.JButton btnUrediDobavljaca;
    private javax.swing.JButton btnUrediKupca;
    private javax.swing.JButton btnUrediZaposlenik;
    private javax.swing.JComboBox<Dobavljac> cmbDobavljaci;
    private javax.swing.JComboBox<Kupac> cmbKupci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelZap;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBrojRacuna;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblTrenutniDatum;
    private javax.swing.JLabel lblTrenutniZaposlenik;
    private javax.swing.JLabel lblUkCijena;
    private javax.swing.JLabel lblVrijeme;
    private javax.swing.JLabel lblZaposlenik;
    private javax.swing.JList<Artikl> lstArtikli;
    private javax.swing.JList<Dobavljac> lstDobavljaci;
    private javax.swing.JList<Kupac> lstKupci;
    private javax.swing.JList<Narudzba> lstNarudzbe;
    private javax.swing.JList<Artikl> lstSveStavke;
    private javax.swing.JList<edunova.jp23.model.Stavka> lstTrenutneStavke;
    private javax.swing.JList<Operater> lstZaposlenici;
    private javax.swing.JPanel paneArtikl;
    private javax.swing.JPanel paneDobavljac;
    private javax.swing.JPanel paneKupci;
    private javax.swing.JPanel paneNarudzba;
    private javax.swing.JPanel paneZaposlenik;
    private javax.swing.JPasswordField pwdZaporkaZaposlenika;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtAdresaDobavljaca;
    private javax.swing.JTextField txtAdresaKupca;
    private javax.swing.JTextField txtCijenaArtikla;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailKupca;
    private javax.swing.JTextField txtIban;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtImeKupca;
    private javax.swing.JTextField txtImeVlasnikaDobavljaca;
    private javax.swing.JTextField txtKontaktKupca;
    private javax.swing.JTextField txtNazivArtikla;
    private javax.swing.JTextField txtNazivDobavljaca;
    private javax.swing.JTextField txtOib;
    private javax.swing.JTextField txtOibKupca;
    private javax.swing.JTextField txtPretraga;
    private javax.swing.JTextField txtPretraziArtikli;
    private javax.swing.JTextField txtPretraziKupce;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtPrezimeKupca;
    private javax.swing.JTextField txtTraziDobavljace;
    // End of variables declaration//GEN-END:variables

    private class Vrijeme extends Thread{
        
        private SimpleDateFormat df = 
                new SimpleDateFormat("dd. MMMM YYYY. HH:mm:ss");

        @Override
        public void run() {
            while (true) {                
                lblVrijeme.setText(df.format(new Date()));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                }
            }
        }
        
    }
        
    private void ucitajEntitete(){
        DefaultListModel<Narudzba> m = new DefaultListModel<>();

        //m.addAll(obrada.getPodaci());
        System.out.println("Narudžbe");
        obradaN.getPodaci().forEach(xxxx -> {
            m.addElement(xxxx);
            System.out.println(
                    xxxx.getArtikli().hashCode());
        });

        lstNarudzbe.setModel(m);
    }
    
    private void ucitajKupce() {
         
        DefaultComboBoxModel<Kupac> m =
                 new DefaultComboBoxModel<>();
        Kupac k=new Kupac();
        k.setId(-1L);
        k.setIme("Odaberite kupca");
        m.addElement(k);
        System.out.println("Kupci u CMB");
        new ObradaKupac().getPodaci().forEach(sm->{
              m.addElement(sm);
              System.out.println(sm.getIme()+" "+sm.getPrezime()+ ": " + 
                      sm.hashCode());
         });

        cmbKupci.setModel(m);
        cmbKupci.setSelectedIndex(0);
        
    }
    

    private void postaviVrijednostiNaEntitet() {
       var g = obradaN.getEntitet();
       g.setKupac((Kupac)cmbKupci.getSelectedItem());
       g.setDatum(new Date());
       g.setOperater(Aplikacija.operater);
       
       
       DefaultListModel<Stavka> m;
        try {
            m=(DefaultListModel<Stavka>) lstTrenutneStavke.getModel();
            g.setArtikli(new ArrayList<>());
            for(int i=0;i<m.getSize();i++){
                g.getArtikli().add(m.get(i));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        updateUkupnaCijena();
       
       
       lstTrenutneStavke.repaint();
       
    }
    
    
    
    
    
    private void pocisti() {
        lblDatum.setText("");
        lblTrenutniZaposlenik.setText("");
        lblVrijeme.setText("");
        lstTrenutneStavke.removeAll();
        lblBrojRacuna.setText("Broj računa: ");
        lblUkCijena.setText("");
        lstTrenutneStavke.removeAll();

    }
//Operatori panel:
        
        private void ucitajO() {

        DefaultListModel<Operater> m = new DefaultListModel<>();

        m.addAll(obradaO.getPodaci());

        lstZaposlenici.setModel(m);

    }

    private void postaviVrijednostiNaEntitetO() {
        var entitet=obradaO.getEntitet();
        
        entitet.setIme(txtIme.getText());

        try {
            entitet.setPrezime(txtPrezime.getText());
        } catch (Exception e) {
            entitet.setPrezime("");
        }

        try {
            entitet.setEmail(txtEmail.getText());
        } catch (Exception e) {
            entitet.setEmail("");
        }
        try {
            entitet.setIban(txtIban.getText());
        } catch (Exception e) {
            entitet.setIban("");
        }

        try {
            entitet.setOib(txtOib.getText());
        } catch (Exception e) {
            entitet.setOib("");
        }
        String lozinka = new String(pwdZaporkaZaposlenika.getPassword());
        try{
            entitet.setLozinka(BCrypt.hashpw(lozinka, BCrypt.gensalt()));
        }catch(Exception e){
            entitet.setLozinka("");
        }

    }

    private void pocistiO() {
        txtPrezime.setText("");
        txtIme.setText("");
        txtEmail.setText("");
        txtOib.setText("");
        txtIban.setText("");
        

    }
    //Artikl panel:
    private void ucitajDobavljaceCmb(){
        DefaultComboBoxModel<Dobavljac> m =
                 new DefaultComboBoxModel<>();
        Dobavljac d=new Dobavljac();
        d.setId(-1L);
        d.setNaziv("Odaberite dobavljača");
        m.addElement(d);
        System.out.println("Dobavljači u CMB");
        new ObradaDobavljac().getPodaci().forEach(sm->{
              m.addElement(sm);
              System.out.println(sm.getNaziv()+" "+ 
                      sm.hashCode());
         });

        cmbDobavljaci.setModel(m);
        cmbDobavljaci.setSelectedIndex(0);
    }
    
    private void pocistiA(){
        txtNazivArtikla.setText("");
        txtCijenaArtikla.setText("");
        cmbDobavljaci.setSelectedIndex(0);
    }
    
    private void ucitajA(){
        DefaultListModel<Artikl> m = new DefaultListModel<>();

        m.addAll(obradaA.getPodaci());

        lstArtikli.setModel(m);
    }
    
    private void postaviVrijednostiNaEntitetA() {
        var entitet=obradaA.getEntitet();
        
        entitet.setNaziv(txtNazivArtikla.getText());
        entitet.setCijena(new BigDecimal(txtCijenaArtikla.getText()));
        entitet.setDobavljac((Dobavljac)cmbDobavljaci.getSelectedItem());
        
    }
    
    
    //Dobavljači panel:
    private void pocistiD(){
        txtNazivDobavljaca.setText("");
        txtAdresaDobavljaca.setText("");
        txtImeVlasnikaDobavljaca.setText("");
    }
    
    private void ucitajD(){
        DefaultListModel<Dobavljac> m = new DefaultListModel<>();

        m.addAll(obradaD.getPodaci());

        lstDobavljaci.setModel(m);
    }
    
    private void postaviVrijednostiNaEntitetD(){
        var entitet=obradaD.getEntitet();
        
        entitet.setNaziv(txtNazivDobavljaca.getText());
        entitet.setAdresa(txtAdresaDobavljaca.getText());
        entitet.setImeVlasnika(txtImeVlasnikaDobavljaca.getText());
    }
    
    //Kupci panel:
    private void pocistiK(){
        txtImeKupca.setText("");
        txtPrezimeKupca.setText("");
        txtOibKupca.setText("");
        txtAdresaKupca.setText("");
        txtKontaktKupca.setText("");
        txtEmailKupca.setText("");
    }
    
    private void ucitajK(){
        DefaultListModel<Kupac> m = new DefaultListModel<>();

        m.addAll(obradaK.getPodaci());

        lstKupci.setModel(m);
    }
    
    private void postaviVrijednostiNaEntitetK(){
        var entitet=obradaK.getEntitet();
        
        entitet.setIme(txtImeKupca.getText());
        entitet.setPrezime(txtPrezimeKupca.getText());
        entitet.setAdresa(txtAdresaKupca.getText());
        entitet.setEmail(txtEmailKupca.getText());
        entitet.setOib(txtOibKupca.getText());
        entitet.setKontakt(txtKontaktKupca.getText());
    }
    
    private BigDecimal updateUkupnaCijena(){
        BigDecimal ukupnaCijena = BigDecimal.ZERO;
        if(lstNarudzbe.getSelectedValue()==null){
            return BigDecimal.ZERO;
        }
        for(Stavka s : lstNarudzbe.getSelectedValue().getArtikli()){
            ukupnaCijena=ukupnaCijena.add(s.getArtikl().getCijena());
        }
        
        System.out.println(ukupnaCijena.toString());;
        
        return ukupnaCijena;
        
       
    }
    public void postavljanjeVrijednosti(){
        var g= obradaN.getEntitet();

        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        
        
        lblZaposlenik.setText(Aplikacija.operater.getImePrezime());
        lblBrojRacuna.setText("Broj računa: "+ g.getId());
        cmbKupci.setSelectedItem(g.getKupac());
        lblDatum.setText(df.format(g.getDatum()));
        lstNarudzbe.getSelectedValue().setUkupnaCijena(updateUkupnaCijena());
        lblUkCijena.setText(g.ukupnaCijenaToString());
    }
        
    

        
        
    }
    
    
   




